import { readdir, readFile, writeFile } from "node:fs/promises";
import { extname, join, relative, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const dist = join(root, "dist");
const output = join(root, "convex", "generatedStatic.ts");

const contentTypes = {
  ".css": "text/css; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
};

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await walk(path));
    else files.push(path);
  }
  return files;
}

const files = await walk(dist);
const entries = await Promise.all(files.map(async (file) => {
  const path = `/${relative(dist, file).replaceAll("\\\\", "/")}`;
  const body = (await readFile(file)).toString("base64");
  return [path, { body, contentType: contentTypes[extname(file)] ?? "application/octet-stream" }];
}));

const generated = `// Generated by scripts/embed-static.mjs. Do not edit by hand.\n` +
  `export const STATIC_FILES: Record<string, { body: string; contentType: string }> = ${JSON.stringify(Object.fromEntries(entries))};\n`;

await writeFile(output, generated);
console.log(`Embedded ${entries.length} production files for Convex static hosting.`);
